language: python
python:
    - 2.6
    - 2.7
install:
    - python setup.py install
sudo: required
env:
    - SPAMD_SOCK=/var/run/spamd.sock SPAMD_COMPRESS=1
script: python setup.py nosetests
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install spamassassin
    - echo 'ENABLED=1' | sudo tee -a /etc/default/spamassassin
    - echo 'OPTIONS="--listen=127.0.0.1 --socketpath=/var/run/spamd.sock --socketmode=0777 -d -l -m5"' | sudo tee -a /etc/default/spamassassin
    - sudo service spamassassin start
before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements/requirements26_dev.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements/requirements27_dev.txt; fi
    - pip install codecov
after_success:
    - codecov
branches:
    only:
        - master
        - testing
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
        - andrew@topdog.za.net
